use crate::traits::Extractor;
use crate::types::{ExtractInput, ExtractOutput, MatchInput, MatchOutput};

/// ABI version implemented by this SDK; returned by `goaria_abi_version`.
pub const CURRENT_ABI_VERSION: u32 = 1;
/// Required export: returns [`CURRENT_ABI_VERSION`] to the host.
pub const ABI_EXPORT_VERSION: &str = "goaria_abi_version";
/// Required export: guest allocator the host calls to reserve guest memory
/// before writing input buffers.
pub const ABI_EXPORT_ALLOC: &str = "goaria_alloc";
/// Required export: guest deallocator the host calls to release buffers it
/// allocated via `goaria_alloc` or received back from guest entrypoints.
pub const ABI_EXPORT_FREE: &str = "goaria_free";
/// Required export: URL-matching entrypoint (`MatchInput` -> `MatchOutput`).
pub const ABI_EXPORT_MATCH: &str = "goaria_match";
/// Required export: extraction entrypoint (`ExtractInput` -> `ExtractOutput`).
pub const ABI_EXPORT_EXTRACT: &str = "goaria_extract";

/// Wasm module namespace under which the host provides its imports.
pub const HOST_IMPORT_MODULE: &str = "goaria_host";
/// Host import: brokered HTTP fetch (`cap.http.fetch`).
pub const HOST_IMPORT_HTTP_FETCH: &str = "http_fetch";
/// Host import: auth-profile availability query (`cap.auth.profile`).
pub const HOST_IMPORT_AUTH_PROFILE_STATUS: &str = "auth_profile_status";

/// Pack a guest-memory pointer and a buffer length into the 64-bit value the
/// ABI uses to return dynamic buffers: high 32 bits are the byte offset of
/// the payload in the exported `"memory"`, low 32 bits are the byte length.
/// A return of `0` signals failure or an empty payload.
#[inline]
pub const fn pack_result(ptr: u32, len: u32) -> u64 {
    ((ptr as u64) << 32) | (len as u64)
}

/// Inverse of [`pack_result`]: split a 64-bit ABI return value into its
/// `(ptr, len)` components.
#[inline]
pub const fn unpack_result(packed: u64) -> (u32, u32) {
    ((packed >> 32) as u32, packed as u32)
}

/// Serialize `value` to JSON in guest memory and return the packed
/// `ptr << 32 | len` handle.
///
/// The returned buffer is allocated via [`crate::alloc::alloc`], so ownership
/// passes to the host, which releases it by calling `goaria_free`. Returns
/// `0` if serialization or allocation fails.
pub fn pack_json_response<T: serde::Serialize>(value: &T) -> i64 {
    match serde_json::to_vec(value) {
        Ok(bytes) => {
            let (ptr, len) = unsafe { crate::alloc::copy_slice_to_guest(&bytes) };
            pack_result(ptr as u32, len as u32) as i64
        }
        Err(_) => 0,
    }
}

/// Dispatcher behind the `goaria_match` export generated by
/// `#[goaria_extractor]`.
///
/// Decodes `MatchInput` from the host-provided buffer, runs
/// `E::default().match_url`, and returns the packed `MatchOutput` JSON.
/// A malformed buffer or undecodable input maps to `matched: false` with a
/// `reason`; an `Err` from `match_url` maps to `matched: false` with the
/// error text as `reason`.
///
/// On `wasm32-unknown-unknown` the default `panic=abort` strategy turns a
/// panic into an `unreachable` trap that the host runtime isolates;
/// `catch_unwind` cannot recover it. On native test builds the dispatcher
/// additionally catches unwinding panics and reports them as a negative
/// match.
///
/// # Safety
/// `ptr`/`len` must designate a readable guest-memory buffer for the
/// duration of the call. Under the ABI the host owns that input buffer and
/// frees it after the call returns; the guest must not free or retain it.
pub unsafe fn dispatch_match<E: Extractor + Default>(ptr: i32, len: i32) -> i64 {
    if ptr == 0 || len <= 0 {
        return pack_json_response(&MatchOutput {
            matched: false,
            confidence: None,
            reason: Some("invalid input buffer pointer or length".to_string()),
        });
    }

    let raw = crate::alloc::ptr_to_raw(ptr);
    if raw.is_null() {
        return pack_json_response(&MatchOutput {
            matched: false,
            confidence: None,
            reason: Some("invalid input buffer pointer".to_string()),
        });
    }

    let input_bytes = std::slice::from_raw_parts(raw, len as usize);
    let input: MatchInput = match serde_json::from_slice(input_bytes) {
        Ok(inp) => inp,
        Err(e) => {
            return pack_json_response(&MatchOutput {
                matched: false,
                confidence: None,
                reason: Some(format!("failed to parse match input JSON: {}", e)),
            });
        }
    };

    #[cfg(target_arch = "wasm32")]
    let output = match E::default().match_url(input) {
        Ok(output) => output,
        Err(err) => MatchOutput {
            matched: false,
            confidence: None,
            reason: Some(err.to_string()),
        },
    };

    #[cfg(not(target_arch = "wasm32"))]
    let output = match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        E::default().match_url(input)
    })) {
        Ok(Ok(output)) => output,
        Ok(Err(err)) => MatchOutput {
            matched: false,
            confidence: None,
            reason: Some(err.to_string()),
        },
        Err(_) => MatchOutput {
            matched: false,
            confidence: None,
            reason: Some("guest panicked during match_url".to_string()),
        },
    };

    pack_json_response(&output)
}

/// Dispatcher behind the `goaria_extract` export generated by
/// `#[goaria_extractor]`.
///
/// Decodes `ExtractInput` from the host-provided buffer and runs
/// `E::default().extract`. ABI v1 defines no error envelope for extraction:
/// a malformed buffer, undecodable input, an `Err` result, or (on native
/// builds) a caught panic all map to an empty `ExtractOutput`.
///
/// On `wasm32-unknown-unknown` the default `panic=abort` strategy turns a
/// panic into an `unreachable` trap that the host runtime isolates;
/// `catch_unwind` cannot recover it.
///
/// # Safety
/// `ptr`/`len` must designate a readable guest-memory buffer for the
/// duration of the call. Under the ABI the host owns that input buffer and
/// frees it after the call returns; the guest must not free or retain it.
pub unsafe fn dispatch_extract<E: Extractor + Default>(ptr: i32, len: i32) -> i64 {
    if ptr == 0 || len <= 0 {
        return pack_json_response(&ExtractOutput::default());
    }

    let raw = crate::alloc::ptr_to_raw(ptr);
    if raw.is_null() {
        return pack_json_response(&ExtractOutput::default());
    }

    let input_bytes = std::slice::from_raw_parts(raw, len as usize);
    let input: ExtractInput = match serde_json::from_slice(input_bytes) {
        Ok(inp) => inp,
        Err(_) => {
            return pack_json_response(&ExtractOutput::default());
        }
    };

    #[cfg(target_arch = "wasm32")]
    let output = E::default().extract(input).unwrap_or_default();

    #[cfg(not(target_arch = "wasm32"))]
    let output =
        std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| E::default().extract(input)))
            .ok()
            .and_then(Result::ok)
            .unwrap_or_default();

    pack_json_response(&output)
}
